name: Release App

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust environment with nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install cargo-binstall
        run: |
          wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          mkdir -p /usr/local/cargo/bin
          cp cargo-binstall /usr/local/cargo/bin

      - name: Install cargo-leptos
        run: |
          cargo binstall cargo-leptos -y

      - name: Add the WASM target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Build app with cargo-leptos
        run: |
          cargo leptos build --release -vv

      - name: Prepare app/ directory for release
        run: |
          tar -czf app-linux.tar.gz -C app .

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./app-linux.tar.gz
          asset_name: app-linux.tar.gz
          asset_content_type: application/gzip

  release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust environment with nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: x86_64-pc-windows-msvc

      - name: Install cargo-binstall
        env:
          CARGO_HOME: ${{ runner.temp }}/cargo
        run: |
          Invoke-WebRequest -Uri https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-pc-windows-msvc.zip -OutFile cargo-binstall.zip
          Expand-Archive cargo-binstall.zip -DestinationPath .
          mkdir $env:CARGO_HOME\\bin
          Copy-Item .\\cargo-binstall.exe $env:CARGO_HOME\\bin\\

      - name: Install cargo-leptos
        run: |
          cargo binstall cargo-leptos -y

      - name: Add the WASM target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Build app with cargo-leptos
        run: |
          cargo leptos build --release -vv

      - name: Prepare app/ directory for release
        run: |
          Compress-Archive -Path app\\* -DestinationPath app-windows.zip

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./app-windows.zip
          asset_name: app-windows.zip
          asset_content_type: application/zip
