name: Release App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust environment with nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install cargo-leptos
        run: |
          cargo binstall cargo-leptos -y

      - name: Add the WASM target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Build app with cargo-leptos
        run: |
          cargo leptos build --release -vv

      - name: Prepare release package
        run: |
          mkdir -p release-package/target
          cp target/release/shut_remote release-package/
          cp -r target/site release-package/target/
          tar -czf shut_remote-linux.tar.gz -C release-package .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shut_remote-linux.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust environment with nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: x86_64-pc-windows-msvc
          override: true

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install cargo-leptos
        run: |
          cargo binstall cargo-leptos -y

      - name: Add the WASM target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Build app with cargo-leptos
        run: |
          cargo leptos build --release -vv

      - name: Prepare release package
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path release-package\target -Force
          Copy-Item target\release\shut_remote.exe release-package\
          Copy-Item target\site release-package\target\site -Recurse
          Compress-Archive -Path release-package\* -DestinationPath shut_remote-windows.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shut_remote-windows.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
